apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonteste
spec:
  selector:
    matchLabels:
      app: pythonteste
  template:
    metadata:
      labels:
        app: pythonteste
    spec:
      containers:
      - name: pythonteste
        image: pythonteste:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: pythonteste
spec:
  selector:
    app: pythonteste
  ports:
  - port: 2530
    targetPort: 5000
